export const orders = [
  {
    id: "1",
    datestamp: "2019-09-18 10:35:40",
    last_update: "2019-09-22 09:27:37",
    status: "",
    subtotal: "1117.00",
    tax: "78.19",
    shipping: "15.00",
    discount: "335.10",
    total: "875.09",
    customer_id: "1",
    birthday: "1982-11-1",
    city: "",
    company: "Offset Partners",
    credit_number: "9999",
    credit_type: "Visa",
    email: "tyson@commercebyfigure.com",
    first_name: "Tyson",
    gift_message: "Happy Birthday!",
    inventory_location: "Website",
    is_club_member: "Yes",
    item_count: "3",
    last4: "9999",
    last_name: "Caly",
    order_id: "1",
    payment_status: "Paid",
    phone: "707-287-6262",
    shipping_address: "523 Brown St",
    shipping_address_2: "",
    shipping_city: "Napa",
    shipping_company: "Offset Partners",
    shipping_first_name: "Tyson",
    shipping_last_name: "Caly",
    shipping_method: "1",
    shipping_method_carrier: "",
    shipping_method_code: "UPSGND",
    shipping_method_name: "Ground",
    shipping_phone: "707-287-5906",
    shipping_state: "CA",
    shipping_zip: "94559",
    ship_status: "Not Shipped",
    products: [
      {
        id: "1",
        sku: "AA1003",
        name: "Verite La Muse 2014",
        type: "",
        bottle_size: "750mL",
        retail_price: "399.00",
        discount: "0.00",
        discount_type: "",
        price: "399",
        quantity: "5",
        status: "",
        inventory_location: "",
        state: "",
        description: "Verite La Muse 2014 ",
        image: "",
        stock_status: "",
        product_channel: "",
        shipped: "0",
        created: "2019-09-18 10:35:41",
      },
      {
        id: "1",
        sku: "AA1004",
        name: "Verite Le Desir 2014",
        type: "",
        bottle_size: "750mL",
        retail_price: "359.00",
        discount: "0.00",
        discount_type: "",
        price: "359",
        quantity: "1",
        status: "",
        inventory_location: "",
        state: "",
        description: "Verite Le Desir 2014 ",
        image: "",
        stock_status: "",
        product_channel: "",
        shipped: "0",
        created: "2019-09-18 10:35:41",
      },
      {
        id: "1",
        sku: "AA1005",
        name: "Verite La Joie 2014",
        type: "",
        bottle_size: "750mL",
        retail_price: "359.00",
        discount: "0.00",
        discount_type: "",
        price: "359",
        quantity: "1",
        status: "",
        inventory_location: "",
        state: "",
        description: "Verite La Joie 2014 ",
        image: "",
        stock_status: "",
        product_channel: "",
        shipped: "0",
        created: "2019-09-18 10:35:41",
      },
    ],
  },
  {
    id: "2",
    datestamp: "2019-09-19 14:37:37",
    last_update: "2019-09-19 14:44:09",
    status: "",
    subtotal: "0.00",
    tax: "0.00",
    shipping: "0.00",
    discount: "0.00",
    credits: "0.00",
    refund: "186.47",
    total: "0.00",
    customer_id: "1",
    birthday: "1982-11-1",
    cancellation_reason: "Financial burden",
    cancelled_date: "2019-09-19 14:44:19",
    city: "Napa",
    company: "",
    credit_id: "74",
    credit_number: "9969",
    credit_type: "Visa",
    customer_credits: "0.00",
    discount_customer: "20",
    email: "tyson@commercebyfigure.com",
    first_name: "Tyson",
    gift_message: "",
    group_name: "Test Group",
    instructions: "",
    inventory_location: "Website",
    item_count: "3",
    last_name: "Caly",
    order_id: "2",
    order_type: "Offering",
    payment_status: "Paid",
    phone: "707-287-6262",
    requested_ship_date: "2017-09-20",
    sales_agent: "Customer",
    salutation: "Mr.",
    shipping_address: "523 Brown St",
    shipping_address_2: "",
    shipping_city: "Napa",
    shipping_company: "Offset Partners",
    shipping_country: "US",
    shipping_email: "Info@commercebyfigure.com",
    shipping_first_name: "Tyson",
    shipping_id: "1",
    shipping_last_name: "Caly",
    shipping_method: "1",
    shipping_method_carrier: "",
    shipping_method_code: "UPSGND",
    shipping_method_name: "Ground",
    shipping_phone: "707-287-5906",
    shipping_state: "CA",
    shipping_title: "",
    shipping_zip: "94559",
    ship_status: "Cancelled",
    state: "CA",
    sub_group: "Tier 1",
    tax_method: "StateRates",
    tax_rate: "10",
    tax_state: "CA",
    transaction_id: "2",
    wishlist_original_request:
      '{"AA1001":{"sku":"AA1001","quantity":"3","description":"Philip Togni Cabernet Sauvignon Tanbark Hill 2015","price":"64.95","expires":"0000-00-00 00:00:00","session":"Wish-1-2","retail_price":"0.00","discount":"0.00","discount_type":"","location":"","reserve_inventory":"0"}}',
    wishlist_session_id: "Wish-1-2",
    zip: "94559",
    products: [
      {
        id: "2",
        sku: "AA1001",
        name: "Philip Togni Cabernet Sauvignon Tanbark Hill 2015",
        type: "",
        bottle_size: "750mL",
        retail_price: "0.00",
        discount: "0.00",
        discount_type: "",
        price: "64.95",
        quantity: "3",
        status: "Cancelled",
        inventory_location: "",
        state: "",
        description: "Philip Togni Cabernet Sauvignon Tanbark Hill 2015 ",
        image: "",
        stock_status: "",
        product_channel: "",
        shipped: "0",
        created: "2019-09-19 14:37:39",
      },
      {
        id: "2",
        sku: "AA1001",
        name: "Philip Togni Cabernet Sauvignon Tanbark Hill 2015",
        type: "",
        bottle_size: "750mL",
        retail_price: "0.00",
        discount: "0.00",
        discount_type: "",
        price: "64.95",
        quantity: "-3",
        status: "",
        inventory_location: "",
        state: "",
        description: "Philip Togni Cabernet Sauvignon Tanbark Hill 2015 ",
        image: "",
        stock_status: "",
        product_channel: "",
        shipped: "0",
        created: "2019-09-19 14:44:09",
      },
    ],
  },
  {
    id: "4",
    datestamp: "2019-09-22 19:19:59",
    last_update: "2019-09-27 19:17:23",
    status: "",
    subtotal: "1117.00",
    tax: "89.36",
    shipping: "15.00",
    discount: "223.40",
    credits: "0.00",
    refund: "0.00",
    total: "997.96",
    customer_id: "1",
    actual_ship_date: "2019-10-04",
    birthday: "1982-11-1",
    city: "Napa",
    company: "Offset Partners",
    customer_credits: "0.00",
    discount_customer: "20",
    editable_notes: "Follow up with Joseph",
    email: "tyson@commercebyfigure.com",
    email_template: "",
    first_name: "Tyson",
    free_shipping: "0",
    full_address: "",
    gift_message:
      "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.",
    group_id: "3",
    group_name: "Test Group",
    inventory_location: "Website",
    is_club_member: "Yes",
    item_count: "3",
    last_name: "Caly",
    order_id: "4",
    order_type: "POS",
    payment_id: "74",
    payment_status: "Paid",
    phone: "707-287-6262",
    referral_source: "Event/Tasting",
    requested_ship_date: "2019-10-01",
    sales_agent: "Tyson Caly",
    sale_credit: "Tyson Caly",
    salutation: "Mr.",
    shipping_address: "523 Brown St",
    shipping_address_2: "",
    shipping_birthday: "",
    shipping_city: "Napa",
    shipping_company: "Offset Partners",
    shipping_email: "",
    shipping_first_name: "Tyson",
    shipping_last_name: "Caly",
    shipping_method: "1",
    shipping_method_carrier: "",
    shipping_method_code: "UPSGND",
    shipping_method_id: "1",
    shipping_method_name: "Ground",
    shipping_phone: "707-287-5906",
    shipping_residential: "1",
    shipping_state: "CA",
    shipping_zip: "94559",
    ship_status: "Not Shipped",
    state: "CA",
    tax_rate: "10",
    transaction_id: "5",
    zip: "94559",
    products: [
      {
        id: "4",
        sku: "AA1003",
        name: "Verite La Muse 2014",
        type: "",
        bottle_size: "750mL",
        retail_price: "399.00",
        discount: "0.00",
        discount_type: "",
        price: "399",
        quantity: "1",
        status: "",
        inventory_location: "",
        state: "",
        description: "Verite La Muse 2014 ",
        image: "",
        stock_status: "",
        product_channel: "",
        shipped: "0",
        created: "2019-09-22 19:20:00",
      },
      {
        id: "4",
        sku: "AA1004",
        name: "Verite Le Desir 2014",
        type: "",
        bottle_size: "750mL",
        retail_price: "359.00",
        discount: "0.00",
        discount_type: "",
        price: "359",
        quantity: "1",
        status: "",
        inventory_location: "",
        state: "",
        description: "Verite Le Desir 2014 ",
        image: "",
        stock_status: "",
        product_channel: "",
        shipped: "0",
        created: "2019-09-22 19:20:00",
      },
      {
        id: "4",
        sku: "AA1005",
        name: "Verite La Joie 2014",
        type: "",
        bottle_size: "750mL",
        retail_price: "359.00",
        discount: "0.00",
        discount_type: "",
        price: "359",
        quantity: "1",
        status: "",
        inventory_location: "",
        state: "",
        description: "Verite La Joie 2014 ",
        image: "",
        stock_status: "",
        product_channel: "",
        shipped: "0",
        created: "2019-09-22 19:20:00",
      },
    ],
  },
];

export const customers = [
  {
    id: "1",
    first_name: "Tyson",
    last_name: "Caly",
    email: "tyson@commercebyfigure.com",
    status: "Active",
    state: "CA",
    order_count: "31",
    order_total: "18148.31",
    last_order: "2020-06-04 00:00:00",
    last_order_total: "873.60",
    last_update: "2020-08-06 08:28:37",
    created: "2017-12-01 16:06:31",
    active_account: "Yes",
    address: "770 3rd St E",
    address_2: "",
    agreed_to_mailing_list: "Yes",
    agreed_to_terms_privacy: "Yes",
    alt_admin_notes: "",
    alt_payment_notes: "Corporate card is Amex",
    alt_shipping_notes: "Use FedEx Only. Nc",
    billing_address: "523 Brown St",
    billing_address_2: "",
    billing_city: "Napa",
    billing_state: "CA",
    billing_zip: "94559",
    birthday: "1982-11-01",
    children: "",
    city: "Sonoma",
    clubs: "Acme Refreshing Whites Club,VIP Club",
    company: "Offset Partners",
    consent_date: "2020-06-01",
    consent_time: "16:18:26",
    created_by: "Tori Williams",
    created_date: "2017-05-15",
    created_time: "11:19",
    customer_source: "Web",
    customer_type: "",
    job_title: "Partner / Technology",
    last_name_spouse: "",
    mailing_address: "523 Brown St",
    mailing_address_2: "",
    mailing_city: "Napa",
    mailing_company: "Offset Partners",
    mailing_country: "",
    mailing_state: "CA",
    mailing_zip: "94559",
    mail_marketing_opt_in: "Yes",
    mail_marketing_opt_in_update: "",
    marketing_opt_in: "Yes",
    phone_call_opt_in: "Yes",
    referral_code: "",
    referral_note: "Graton",
    referral_source: "Other",
    salutation: "Mr",
    spouse_phone: "",
    sub_group: "",
    temporary_customer_notes: "",
    vip_pickup: "No",
    work: "",
    zip: "95476",
  },
];
