export const orders = [
  {
    id: "1",
    datestamp: "2019-09-18 10:35:40",
    last_update: "2019-09-22 09:27:37",
    status: "",
    subtotal: "1117.00",
    tax: "78.19",
    shipping: "15.00",
    discount: "335.10",
    total: "875.09",
    customer_id: "1",
    birthday: "1982-11-1",
    city: "",
    company: "Offset Partners",
    credit_number: "9999",
    credit_type: "Visa",
    email: "tyson@commercebyfigure.com",
    first_name: "Tyson",
    gift_message: "Happy Birthday!",
    inventory_location: "Website",
    is_club_member: "Yes",
    item_count: "3",
    last4: "9999",
    last_name: "Caly",
    order_id: "1",
    payment_status: "Paid",
    phone: "707-287-6262",
    shipping_address: "523 Brown St",
    shipping_address_2: "",
    shipping_city: "Napa",
    shipping_company: "Offset Partners",
    shipping_first_name: "Tyson",
    shipping_last_name: "Caly",
    shipping_method: "1",
    shipping_method_carrier: "",
    shipping_method_code: "UPSGND",
    shipping_method_name: "Ground",
    shipping_phone: "707-287-5906",
    shipping_state: "CA",
    shipping_zip: "94559",
    ship_status: "Not Shipped",
  },
];

export const customers = [
  {
    id: "1",
    first_name: "Tyson",
    last_name: "Caly",
    email: "tyson@commercebyfigure.com",
    status: "Active",
    state: "CA",
    order_count: "31",
    order_total: "18148.31",
    last_order: "2020-06-04 00:00:00",
    last_order_total: "873.60",
    last_update: "2020-08-06 08:28:37",
    created: "2017-12-01 16:06:31",
    active_account: "Yes",
    address: "770 3rd St E",
    address_2: "",
    agreed_to_mailing_list: "Yes",
    agreed_to_terms_privacy: "Yes",
    alt_admin_notes: "",
    alt_payment_notes: "Corporate card is Amex",
    alt_shipping_notes: "Use FedEx Only. Nc",
    billing_address: "523 Brown St",
    billing_address_2: "",
    billing_city: "Napa",
    billing_state: "CA",
    billing_zip: "94559",
    birthday: "1982-11-01",
    children: "",
    city: "Sonoma",
    clubs: "Acme Refreshing Whites Club,VIP Club",
    company: "Offset Partners",
    consent_date: "2020-06-01",
    consent_time: "16:18:26",
    created_by: "Tori Williams",
    created_date: "2017-05-15",
    created_time: "11:19",
    customer_source: "Web",
    customer_type: "",
    job_title: "Partner / Technology",
    last_name_spouse: "",
    mailing_address: "523 Brown St",
    mailing_address_2: "",
    mailing_city: "Napa",
    mailing_company: "Offset Partners",
    mailing_country: "",
    mailing_state: "CA",
    mailing_zip: "94559",
    mail_marketing_opt_in: "Yes",
    mail_marketing_opt_in_update: "",
    marketing_opt_in: "Yes",
    phone_call_opt_in: "Yes",
    referral_code: "",
    referral_note: "Graton",
    referral_source: "Other",
    salutation: "Mr",
    spouse_phone: "",
    sub_group: "",
    temporary_customer_notes: "",
    vip_pickup: "No",
    work: "",
    zip: "95476",
  },
];
